name = "SphericalHarmonicArrays"
uuid = "9dd28c12-4719-4e7d-b634-e7b733a6d046"
version = "0.4.0"

[deps]
OffsetArrays = "6fe1bfb0-de20-5000-8ca7-80f57d26f881"
SphericalHarmonicModes = "0e9554e2-b38b-11e9-16d7-9d9abfec665a"

[compat]
OffsetArrays = "0.11, 1.0"
SphericalHarmonicModes = "0.4"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[targets]
test = ["Test", "LinearAlgebra"]
